import Navbar from "./components/Navbar";
import HomePage from "./components/HomePage"
import "./globals.css";
import LoginForm from "./components/LoginForm";

export const metadata = {
  title: "apds",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt">
      <body>
        <div>
          <Navbar/>
        </div>
        <div>
          <HomePage/>
        </div>
      </body>
    </html>
  );
}
